# Generated by Django 4.1 on 2022-12-09 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], default='1'),
        ),
    ]
