# Generated by Django 4.1 on 2022-11-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoworkingSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('alamat', models.CharField(max_length=200)),
                ('harga', models.CharField(max_length=100)),
                ('kapsitas', models.CharField(default='1', max_length=5)),
                ('detail', models.TextField(null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='static/spaces/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
