# Generated by Django 4.1 on 2022-12-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coworkingSpace', '0002_coworkingspace_favorit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coworkingspace',
            name='harga',
            field=models.IntegerField(),
        ),
    ]
