# Generated by Django 4.1 on 2022-12-10 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coworkingSpace', '0003_alter_coworkingspace_harga'),
        ('coworkingSpace', '0003_rename_kapsitas_coworkingspace_kapasitas'),
    ]

    operations = [
    ]
