# Generated by Django 4.1 on 2022-12-09 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coworkingSpace', '0003_alter_coworkingspace_harga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_amount', models.IntegerField(default=0)),
                ('payment_status', models.BooleanField(default=False)),
                ('booking_status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coworking_space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coworkingSpace.coworkingspace')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
