# Generated by Django 4.1 on 2022-12-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='verification_status',
            new_name='payment_status',
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='ticket_amount',
            field=models.IntegerField(default=0),
        ),
    ]
