# Generated by Django 4.1 on 2022-12-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_verification_status_booking_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.BooleanField(default=True),
        ),
    ]
